In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Placement.csv')

In [3]:
df.shape

(215, 15)

In [43]:
df.describe()

,sl_no,ssc_p,ssc_b,hsc_p,degree_p,etest_p,mba_p,salary
count,215.000000,213.000000,215.000000,214.000000,213.000000,215.000000,213.000000,215.000000
mean,108.000000,67.372911,0.455814,66.344065,66.388404,72.208047,62.266103,0.119805
std,62.209324,10.811464,0.508481,10.921885,7.256840,13.193554,5.837303,0.104673
min,1.000000,40.890000,-1.000000,37.000000,50.200000,50.000000,51.210000,0.000000
25%,54.500000,60.800000,0.000000,60.850000,61.000000,60.000000,57.900000,0.067568
50%,108.000000,67.000000,0.000000,65.000000,66.000000,71.000000,62.000000,0.119805
75%,161.500000,76.000000,1.000000,73.000000,72.000000,83.500000,66.230000,0.119805
max,215.000000,89.400000,1.000000,97.700000,91.000000,98.000000,77.890000,1.000000

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 215 entries, 0 to 214
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   sl_no           215 non-null    int64
 1   gender          213 non-null    object
 2   ssc_p           213 non-null    float64
 3   ssc_b           214 non-null    object
 4   hsc_p           214 non-null    float64
 5   hsc_b           213 non-null    object
 6   hsc_s           213 non-null    object
 7   degree_p        213 non-null    float64
 8   degree_t        214 non-null    object
 9   workex          213 non-null    object
 10  etest_p         213 non-null    float64
 11  specialisation  213 non-null    object
 12  mba_p           213 non-null    float64
 13  status          215 non-null    object
 14  salary          148 non-null    float64
dtypes: float64(6), int64(1), object(8)
memory usage: 25.3+ KB

In [5]:
df.head()

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN
4,5,NaN,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0

In [6]:
df.tail()

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
210,211,M,80.6,Others,82.0,Others,Commerce,77.6,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.0
211,212,M,58.0,Others,60.0,Others,Science,72.0,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0
212,213,M,67.0,Others,67.0,Others,Commerce,73.0,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0
213,214,F,74.0,Others,66.0,Others,Commerce,58.0,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0
214,215,M,62.0,Central,58.0,Others,Science,53.0,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,NaN

In [7]:
df.dtypes

sl_no               int64
gender             object
ssc_p             float64
ssc_b              object
hsc_p             float64
hsc_b              object
hsc_s              object
degree_p          float64
degree_t           object
workex             object
etest_p           float64
specialisation     object
mba_p             float64
status             object
salary            float64
dtype: object

In [8]:
df.size

3225

In [9]:
df.columns

Index(['sl_no', 'gender', 'ssc_p', 'ssc_b', 'hsc_p', 'hsc_b', 'hsc_s',
       'degree_p', 'degree_t', 'workex', 'etest_p', 'specialisation', 'mba_p',
       'status', 'salary'],
      dtype='object')

In [10]:
df.sample(10)

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
197,198,F,83.96,Others,53.00,Others,Science,91.00,Sci&Tech,No,59.32,Mkt&HR,69.71,Placed,260000.0
203,204,M,55.68,Others,61.33,Others,Commerce,56.87,Comm&Mgmt,No,66.00,Mkt&HR,58.30,Placed,260000.0
77,78,M,64.00,Others,80.00,Others,Science,65.00,Sci&Tech,Yes,69.00,Mkt&Fin,57.65,Placed,500000.0
60,61,M,74.00,Central,70.00,Central,Science,72.00,Comm&Mgmt,Yes,60.00,Mkt&Fin,57.24,Placed,260000.0
76,77,F,66.50,Others,70.40,Central,Arts,71.93,Comm&Mgmt,No,61.00,Mkt&Fin,64.27,Placed,230000.0
183,184,M,65.00,Central,77.00,Central,Commerce,69.00,Comm&Mgmt,No,60.00,Mkt&HR,61.82,Placed,276000.0
189,190,F,54.00,Central,77.60,Others,Commerce,69.20,Comm&Mgmt,No,95.65,Mkt&Fin,66.94,Not Placed,NaN
125,126,F,84.00,Central,73.00,Central,Commerce,73.00,Comm&Mgmt,No,75.00,Mkt&Fin,73.33,Placed,350000.0
177,178,F,73.00,Central,97.00,Others,Commerce,79.00,Comm&Mgmt,Yes,89.00,Mkt&Fin,70.81,Placed,650000.0
186,187,F,52.00,Central,64.00,Central,Commerce,61.00,Comm&Mgmt,No,55.00,Mkt&Fin,62.93,Not Placed,NaN

In [12]:
df.describe()

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
count,215.000000,213.000000,214.000000,213.000000,213.000000,213.000000,148.000000
mean,108.000000,67.372911,66.344065,66.388404,72.219390,62.266103,288655.405405
std,62.209324,10.811464,10.921885,7.256840,13.255118,5.837303,93457.452420
min,1.000000,40.890000,37.000000,50.200000,50.000000,51.210000,200000.000000
25%,54.500000,60.800000,60.850000,61.000000,60.000000,57.900000,240000.000000
50%,108.000000,67.000000,65.000000,66.000000,71.000000,62.000000,265000.000000
75%,161.500000,76.000000,73.000000,72.000000,84.000000,66.230000,300000.000000
max,215.000000,89.400000,97.700000,91.000000,98.000000,77.890000,940000.000000

In [15]:
df.gender.isna().sum()

2

In [18]:
df['gender'].fillna(df['gender'].mode()[0], inplace = True)

In [19]:
df.gender.isna().sum()

0

In [22]:
df.gender.nunique()

2

In [23]:
df['hsc_s'].fillna(df['hsc_s'].mode()[0], inplace = True)

In [24]:
df.hsc_s.isna().sum()

0

In [31]:
df.isna().sum()

sl_no             0
gender            0
ssc_p             2
ssc_b             1
hsc_p             1
hsc_b             2
hsc_s             0
degree_p          2
degree_t          1
workex            2
etest_p           0
specialisation    2
mba_p             2
status            0
salary            0
dtype: int64

In [30]:
df['etest_p'].fillna(df['etest_p'].median(), inplace = True)

In [34]:
df['salary'].dtypes

string[python]

In [40]:
df['salary'] = df['salary'].astype('float')

In [35]:

df['ssc_b']=df['ssc_b'].astype('category') #change data type to category
df['ssc_b']=df['ssc_b'].cat.codes

In [36]:
df.dtypes

sl_no                      int64
gender                    object
ssc_p                    float64
ssc_b                       int8
hsc_p                    float64
hsc_b                     object
hsc_s                     object
degree_p                 float64
degree_t                  object
workex                    object
etest_p                  float64
specialisation            object
mba_p                    float64
status                    object
salary            string[python]
dtype: object

In [41]:
# Normalization of data
# converting the range of data into uniform range
# marks [0-100] [0-1]
# salary [200000 - 200000 per month] [0-1]
# Min-max feature scaling
# minimum value = 0
# maximum value = 1

# when we design model the higher value over powers in the model
df['salary']=(df['salary']-df['salary'].min())/(df['salary'].max()-df['salary'].min())
# (x - min value into that column)/(max value - min value)

In [42]:
df.salary

0      0.094595
1      0.000000
2      0.067568
3      0.119805
4      0.304054
         ...
210    0.270270
211    0.101351
212    0.128378
213    0.005405
214    0.119805
Name: salary, Length: 215, dtype: float64